name: 'Create or Update StagingDeployCash'
description: 'Creates a new StagingDeployCash issue if there is not one open, or updates the existing one.'
inputs:
    GITHUB_TOKEN:
        description: Auth token for New Expensify Github
        required: true

runs:
    using: 'node16'
    main: './index.js'
