name: PR Author Checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  # Note: PHP specifically looks for the name of this job, "checklist", so if the name of the job is changed,
  # then you also need to go into PHP and update the name of this job in the GH_JOB_NAME_CHECKLIST constant
  checklist:
    runs-on: ubuntu-latest
    if: github.actor != 'OSBotify'
    steps:
      - name: authorChecklist.js
        uses: software-mansion-labs/expensify-app-fork/.github/actions/javascript/authorChecklist@Sebryu-DynamicChecklistPOC
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
