name: Create or update deploy checklist

on:
  workflow_call:
  workflow_dispatch:

jobs:
  createChecklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/composite/setupNode

      - uses: ./.github/actions/javascript/createOrUpdateStagingDeploy
        with:
          GITHUB_TOKEN: ${{ github.token }}
