name: Find Unused styles

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]

jobs:
  perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: Expensify/App/.github/actions/composite/setupNode@main

      - name: Run unused style searcher
        shell: bash
        run: ./.github/scripts/findUnusedKeys.sh

