name: Test GitHub Actions workflows

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches-ignore: [staging, production]
    paths: ['.github']

jobs:
  testGHWorkflows:
    if: ${{ github.actor != 'OSBotify' && github.actor != 'imgbot[bot]' || github.event_name == 'workflow_call' }}
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      fail-fast: false
    name: test GitHub Workflows
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: Expensify/App/.github/actions/composite/setupNode@main

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "Test"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt-get install build-essential
          echo "Homebrew installed"

      - name: Install Act
        run: brew install act

      - name: Run tests
        run: npm run workflow-test
